<h1 style="font-size: 1em;">Smjerovi</h1>
<a href="<?=App::config('url')?>smjer/novo">Dodaj novi smjer</a>
<ul style="list-style-type: none">
<?php foreach($smjerovi as $smjer): ?>
    <li>
        <i title="<?php echo $smjer->verificiran ? 'Verificiran' : 'NIJE verificiran';?>" 
        style="font-size: 1.5em; color:
        <?php echo $smjer->verificiran ? 'green' : 'red';?>" 
        class="fas fa-certificate"></i>
        <span style="font-size: 1.5em;">
        <?=$smjer->naziv?> 
        </span>
        
        <a href="<?=App::config('url')?>smjer/promjena?sifra=<?=$smjer->sifra?>">
            <i title="promjena" class="fas fa-2x fa-pencil-alt"></i>
        </a>
        <?php if($smjer->ukupnogrupa==0): ?>
            <a href="<?=App::config('url')?>smjer/brisanje?sifra=<?=$smjer->sifra?>"
            onclick="return confirm('Sigurno obrisati <?=$smjer->naziv?>?');">
            <i title="brisanje" style="color: red" class="fas fa-trash-alt"></i></a>
        <?php endif;?>
    </li>
<?php endforeach; ?>
</ul>
