<form class="log-in-form" 
    action="<?=App::config('url')?>smjer/novo"
    method="POST">
  <h4 class="text-center">Dodavanje novog smjera</h4>
  <div class="grid-x grid-padding-x">
    <div class="cell">
      <label>Naziv
        <input type="text" name="naziv" value="<?=$smjer->naziv?>">
      </label>
    </div>
  </div>

  <div class="grid-x grid-padding-x">
  <div class="cell large-4">
  <label>Trajanje
    <input type="number" min="1" max="320" name="trajanje" value="<?=$smjer->trajanje?>">
  </label>
  </div>
  <div class="cell large-4">
  <label>Cijena
    <input type="text" name="cijena" value="<?=$smjer->cijena?>">
  </label>
  </div>
  <div class="cell large-4">
  <label>Verificiran
        <select name="verificiran">
        <option 
        <?php 
        if($smjer->verificiran==='1'){
            echo ' selected="selected" ';
        }
        ?>
         value="1">DA</option>


        <option 
        <?php 
        if($smjer->verificiran==='0'){
            echo ' selected="selected" ';
        }
        ?>
         value="0">NE</option>
        </select>
  </label>
  </div>
</div>
 
<div class="grid-x grid-padding-x">
    <div class="cell">
     <div class="callout">
      <?=$poruka?>
     </div>
    </div>
  </div>
  

<div class="grid-x grid-padding-x">
  <div class="cell small-6 medium-6 large-6">
    <a class="alert button expanded" 
        href="<?=App::config('url')?>smjer/index">Nazad</a>
  </div>
  <div class="cell small-6 medium-6 large-6">
    <input type="submit" class="button expanded" value="Dodaj"></input>
  </div>
</div>

</form>